# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True, help_text='性别，True为男性，默认为True'),
        ),
    ]
