# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, help_text='电话号码', verbose_name='电话号码'),
        ),
    ]
