# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180725_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, help_text='生日', null=True),
        ),
    ]
