# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180725_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='地址', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.CharField(blank=True, help_text='职业', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(blank=True, help_text='用户头像', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, help_text='电话号码', null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, default='这家伙很懒，什么签名也没有写！', help_text='个性签名', max_length=256, null=True),
        ),
    ]
